# Generated by Django 3.1.6 on 2021-02-19 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='created_at',
            new_name='created_on',
        ),
    ]
